server:
  port: 8081

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/reactdb?useSSL=false&characterEncoding=UTF-8
    username: totoro
    password: totoro

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.asset.dto
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    # Root 로그 레벨
    root: info
    # Mapper 인터페이스 또는 XML 매퍼가 위치한 패키지 경로 지정 (중요)
    # 아래 경로를 실제 Mapper/DAO 파일이 위치한 패키지명으로 변경해 주세요.
    com.example.asset.mapper: debug